### ISSUE TITLE
Avoid calling cpanm in test suite when NO_NETWORK_TESTING=1 is set

### ISSUE THREAD

**Issue by karenetheridge** [thaljef/Pinto#170]
I just discovered that the low number of cpantesters reports for Task::Kensho::Toolchain might be due to Pinto calling into cpanm (at least 20 times, it looks like!) during its tests  Every call into cpanm creates a new ~/.cpanm/*/build.log, which interferes with cpanm-reporter's ability to find the proper build.log and submit it to the testers network after installation.

Please, could you refrain from running tests that touch the network (including invoking cpanm) when the NO_NETWORK_TESTING environment variable is set?

**Comment by thaljef** [comment]
Starting in 0.09999, there are no (user) tests that require a network. Everything goes to `localhost` and it will do-the-right-thing even if you've set a proxy. Also the by-products of running `cpanm` during the tests are isolated and discarded afterwards.
