### ISSUE TITLE
Error importing APR::Request

### ISSUE THREAD

**Issue by Grissom2nd** [thaljef/Pinto#175]
pinto -r /home/vagrant/repo pull APR::Request
Unable to extract packages from libapreq2-2.13.tar.gz: Failed to upconvert metadata to 1.2. Errors:
Missing mandatory field, 'file' (provides -> APR::Request::CGI -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> APR::Request::Error -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> Apache2::Request -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> APR::Request::Param -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> APR::Request::Cookie -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> Apache2::Upload -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> APR::Request -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> APR::Request::Apache2 -> file) [Validation: 1.2]
Missing mandatory field, 'file' (provides -> Apache2::Cookie -> file) [Validation: 1.2]
 at /usr/local/share/perl/5.10.1/Dist/Metadata.pm line 188.

I'm not shure, who's turn this is, because "Metadata.pm" ist not a pinto-modul, isn't it? 
rgds

**Comment by thaljef** [comment]
This looks resolved (as best it can be).
