### ISSUE TITLE
t/03-remote/05-timezone.t fails because behind "Sophos Web Appliance" controlled network

### ISSUE THREAD

**Issue by muenalan** [thaljef/Pinto#176]
t/03-remote/05-timezone.t .............     
    #   Failed test 'Add action was successful'
    #   at t/03-remote/05-timezone.t line 33.
    
    #   Failed test 'Time offset'
    #   at t/03-remote/05-timezone.t line 39.
    #          got: '0'
    #     expected: '10'
    
    #   Failed test 'User datetime offset'
    #   at t/03-remote/05-timezone.t line 48.
    #          got: '0'
    #     expected: '10'

[snip]

Some html dumped here, with ..

Sophos Web Appliance: File not found

[snip]

**Comment by js21** [comment]
Hi,
I'm contemplating Pinto as the repository management system for the perl applications developed at the Pathogen Informatics team at the Sanger Institute, UK.
I have tested Pinto on my mac and it works brilliantly. I would like to deploy this on our Ubuntu server, but when I try to install it, it fails with a similar error:

# Looks like you failed 3 tests of 9.

#   Failed test 'User vs Local vs UTC time'
#   at t/03-remote/05-timezone.t line 53.
# Looks like you failed 1 test of 1.
t/03-remote/05-timezone.t .............
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/04-server/01-functional.t ........... ok
t/04-server/02-authentication.t ....... ok
t/04-server/03-security.t ............. ok

I would go ahead and force install but I would first like to be sure that this error won't affect Pinto's functionality.

Kind regards,

Jorge

**Comment by js21** [comment]
I guess Pinto will work with no problem.
We aren't looking at using the remote server option, at least for th etime being.

**Comment by thaljef** [comment]
@js21 thanks for considering Pinto. I have never been able to reproduce this particular test failure so I haven't been able to diagnose and fix it yet. However, I can confirm that it has happened in multiple environments so it is not a complete fluke either.

I think the worst that might happen is the timestamps in your commit logs would be displayed in the wrong time zone. And it would only happen if you are using Pinto::Server and Pinto::Remote. So it's not a severe defect, IMHO.

If you decide to go ahead with Pinto, I strongly suggest reading the [Installation Guide](https://metacpan.org/pod/Pinto::Manual::Installing). Depending on your situation, a traditional installation from CPAN may not be your best choice.

Let me know if you have any other questions -- I am always happy to help.

**Comment by js21** [comment]
Hi Jeffrey,
Thanks for getting back to me.
I have gone through the Installation Guide and through most of the documentation.
I find pinto to be a great solution for what I'm intending.

I was wondering, slightly off topic, if there is anyway to install local releases in a specific folder and foreing releases in another folder?

Regards and thanks for writing pinto!

Jorge

**Comment by thaljef** [comment]
> I was wondering, slightly off topic, if there is anyway to install local releases in a specific folder and foreing releases in another folder?

You could install local and foreign releases in separate batches and put them into separate dirs:

```
cpanm -L path/to/foreign/stuff --mirror-only --mirror file://path/to/pinto/repo < LIST_OF_FOREIGN_MODULES

cpanm -L path/to/local/stuff --mirror-only --mirror-file file://path/to/pinto/repo < LIST_OF LOCAL_MODULES
```

That will only work if none of the `FOREIGN_MODULES` depend on `LOCAL_MODULES`. And of course, you'll need to set PERL5LIB to include both `path/to/foreign/stuff` and `/path/to/local/stuff`.

But why do you want to do that anyway?

**Comment by js21** [comment]
Thanks for this info.

That's essentially how our system is setup at the moment. Any external module is installed to an .../external/ folder and the internal ones to an .../internal one.

The procedure ot install the internal modules is very manual though.

I have just had a chat with a coleague and we are happy to completely let go of th eold system.
We can always use pinto list to know which modules are local and which ones are foreign. Plus we can now have a proper Dzil based, dev/prod system for our code.
Also, we will go for the standalone Pinto installation as it makes more sense to have it completely outside of the CPAN work chain.

Thanks for the feedback.

Regards,

Jorge

**Comment by thaljef** [comment]
All tests should now pass, even with no network.
