### ISSUE TITLE
explain why 'add' has a --diff-style option

### ISSUE THREAD

**Issue by tartansandal** [thaljef/Pinto#190]
I may be going mad, but I'm not sure the command `add` would need a `--diff-style` option.  This seems to apply to a number of other commands.  Thinking this maybe a cut and paste error?

**Comment by thaljef** [comment]
All commands that change the contacts of the stack (via the `Comittable` role) can show you a diff of the stack for review.  The --diff-style option controls the format of that diff.

At least that's what I recall (I"m not looking a the code right now).

**Comment by tartansandal** [comment]
Ah, of course. You see a diff in the commit comment. Makes sense. Thanks for the clarification :-)

**Comment by tartansandal** [comment]
This confused me a bit initially -- making me think I did not understand the 'add' command.  Perhaps  the doc could be made to clarify that, if the command succeeds, a commit is going to be made, and this option will change the format of the diff comment in the commit message.  (What a mouthful).  

Of course this is going to apply to all the 'comittable' commands, so it would be good if we could 'template' this pod somehow. I think `Pod::Weaver` may be able to do this. I want to explore using something like that with pod for the proposed mods in #182, so I'll let you know if I can get something working.

**Comment by thaljef** [comment]
Closing. I'll open a separate issue for the "pod template" idea.
