### ISSUE TITLE
Ignore PINTO_HOME and PINTO_AUTHOR_ID during tests

### ISSUE THREAD

**Issue by maxhq** [thaljef/Pinto#196]
**PINTO_HOME**
If there is an existing PINTO_HOME env variable, the test files use intermixed modules from PINTO_HOME and the local blib directories.

    t/03-remote/04-install-with-auth.t .... skipped: Can't open connection to http://localhost:50066
    Module::Runtime version 0.014 required--this is only version 0.013 at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose/Util.pm line 7.
    BEGIN failed--compilation aborted at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose/Util.pm line 7.
    Compilation failed in require at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose/Util/MetaRole.pm line 10.
    BEGIN failed--compilation aborted at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose/Util/MetaRole.pm line 10.
    Compilation failed in require at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose/Exporter.pm line 10.
    BEGIN failed--compilation aborted at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose/Exporter.pm line 10.
    Compilation failed in require at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose.pm line 15.
    BEGIN failed--compilation aborted at /home/maxhq/project/perl-5.20.2/lib/site_perl/5.20.2/x86_64-linux/Moose.pm line 15.
    vvvvvvvvvv
    Compilation failed in require at /opt/pinto/lib/perl5/Pinto/Server.pm line 5.
    BEGIN failed--compilation aborted at /opt/pinto/lib/perl5/Pinto/Server.pm line 5.
    ^^^^^^^^^^
    Compilation failed in require at blib/script/pintod line 27.
    BEGIN failed--compilation aborted at blib/script/pintod line 30.

**PINTO_AUTHOR_ID**
With PINTO_AUTHOR_ID set while installing, the following two tests fail:

    #   Failed test 'Convert username to author id'
    #   at t/01-common/04-util.t line 34.
    #          got: 'MAXHQ'
    #     expected: 'FOOBARBAZ'
    # Looks like you failed 1 test of 40.
    t/01-common/04-util.t ................. 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/40 subtests

**Comment by thaljef** [comment]
Ok, I see how to fix these. Thanks for bringing them to my attention.

**Comment by thaljef** [comment]
This was fixed and released as Pinto-0.09997.
