### ISSUE TITLE
meta.stratopan.com?!?

### ISSUE THREAD

**Issue by marghidanu** [thaljef/Pinto#223]
Hello,

I'm using pinto as a LOCAL perl repository in my infrastructure and today when I wanted to publish a package internally is complaining about not being able to connect to "meta.stratopan.com"...
I'm sorry but this just became unreliable.

**Comment by marghidanu** [comment]
Why is this happening, every time Stratopan is down I can't use the local PRIVATE REPOSITORY?

**Comment by TiMBuS** [comment]
Hello,
Have you tried setting your pinto to not use stratopan? Try editing you <REPO>/.pinto/config/pinto.ini file and changing the `sources` to just cpan. I think that should help.

---

On a similar topic I would like to ask: Is there any way to get our own meta server setup for a private pinto? It's very disappointing that pinto on its own can only work with package indexes, as it stunts the usefulness of things like carton (from a user standpoint). I understand we can use stacks, but I'd prefer to let downstream decide on what they want.

**Comment by marghidanu** [comment]
Thank you, that did the trick. But since stratopan.com has it's ups and downs maybe it should not come as a default in the configuration.

**Comment by thaljef** [comment]
stratopan.com is as reliable as any CPAN mirror and Pinto will fall back to the local index files if it is not available. I apologize for the disruption you experienced, but I don't plan to change the default.
