### ISSUE TITLE
Sort 02packages package name like PAUSE does

### ISSUE THREAD

**Issue by miyagawa** [thaljef/Pinto#226]
It seems Pinto generates 02packages by sorting the package name case sensitively (using perl's built-in sort). https://github.com/thaljef/Pinto/blob/02ca49afb0a940875698bc79ea2953e6b0d38359/lib/Pinto/IndexWriter.pm#L106

PAUSE does it case insensitively, and Pinto should do it the same.
https://github.com/andk/pause/blob/master/lib/PAUSE/mldistwatch.pm#L635

**Comment by xsawyerx** [comment]
Seems like @thaljef released a fix with it. Can be closed.

(Pinto was mentioned at a talk at Barcelona Perl Workshop, so I happened to see this.) :)
