### ISSUE TITLE
`pinto init --help` creates a repository called '--help'

### ISSUE THREAD

**Issue by christopherraa** [thaljef/Pinto#230]
When trying find information about the various pinto commands I ran `pinto init --help` and assumed that this would pull up a manpage. Instead it returned no output but created a repository inside the directory '--help'. This handling of arguments was quite surprising, as I'm used to being provided information on subcommands when appending '--help', see for example `git status --help` and the like.

**Comment by thaljef** [comment]
Pinto relies on App::Cmd for the command line interface. Fortunately, I see that a `--help` option is now built in. So I will update it in the next release. In the meantime, `pinto help <command>` is the equivalent.

**Comment by christopherraa** [comment]
As this issue has been open the past five years I'll close it now.
