### ISSUE TITLE
More information about dependency updates

### ISSUE THREAD

**Issue by schwern** [thaljef/Pinto#56]
When a pull or an add decides it has to update an unpinned dependency, I have to figure this out by reading through the log of what modules will be changed.

Two changes would be handy...

* add & pull tell you what distributions it's updating or adding
* The default commit message for add & pull includes the dependent distribution changes.

Something like this maybe...

```
Add MSCHWERN/Some-Class-1.23.tar.gz

Replacing MSCHWERN/Some-Class-1.22.tar.gz
Add dependency JSCHMOE/Super-Thing-4.23.tar.gz
Update dependency FOO/Bar-1.00.tar.gz to FOO/Bar-1.03.tar.gz
Update dependency FOO/Wibble-0.23.tar.gz to BAR/Wibble-2.43.tar.gz
```

**Comment by thaljef** [comment]
> The default commit message for add & pull includes the dependent distribution changes.

The commit message shows you a diff, much like you described. The `--dry-run` option also shows the diff, so you can see what would have happened. So I think this has been resolved for some time.
