### ISSUE TITLE
pintod needs to drop privileges when it daemonizes (updated)

### ISSUE THREAD

**Issue by hesco** [thaljef/Pinto#69]
Working on this /etc/init.d/pintod script, 
next concern becomes harvesting a pid for the 
starman master so I can shut it down when I 
run the stop target.  

Which led me to study the ps list to discover 
that all the starman processes are running as root.  

Sounds like its time to create a pinto user, 
jail it in the pinto home directory, 
with access only to its pinto repository.  

Kind of freaks me out to open a port to a 
daemon running as root.  I have no idea what 
the escalation paths might be.  But I know what 
the end result would look like and it would not 
be very pretty.  

UPDATE:

Thinking further about this, perhaps the key is to 
create a pinto user before the install, and then run the 
install as the pinto user.

**Comment by bigunyak** [comment]
Hi there,

It looks like the problem reported in this ticket wasn't actually fixed...
All starman processes still run under root user instead of pinto. I believe the fix should be quite simple and only comes to passing ```--user=pinto``` option to ```Plack::Runner->run()``` call in the bin/pintod script.
Could you please fix this?

**Comment by bigunyak** [comment]
Actually, the right place to pass ```--user``` option would be the init.d script.
